/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package triosignin;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/**
 *
 * @author Theo
 */
public class Holder extends javax.swing.JFrame {
    int xSize, ySize;
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    RegistrationForm rm = new RegistrationForm();
    DBConnect db = new DBConnect();
    int mornFrom = 100;
    int mornTo = 600;
    int nightFrom = 2130;
    int nightTo = 2330;
    int delay = 1000 * 60 * 120;
    
    Timer t = new Timer(delay, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            checkTime();
        }
    });
      
    private void checkTime() {
        Date date = new Date();
        Calendar c = Calendar.getInstance();
        c.setTime(date);
        int t = c.get(Calendar.HOUR_OF_DAY) * 100;
        if((t >= mornFrom && t <= mornTo) || (t >= nightFrom && t <= nightTo)) {
            db.closeAllSessions();
        }
    }
        
    public Holder() {
        initComponents(); 
        xSize = (int) screenSize.getHeight();
        ySize = (int) screenSize.getWidth();
        
        this.jPanel2.setSize(ySize, xSize);
        this.jPanel1.setSize(ySize, xSize);
        this.jPanel1.setLocation(0, 0);
        
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(3600, 3600));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jTextField1.setFont(new java.awt.Font("HelveticaNeueLT Std", 1, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        jTextField1.setPreferredSize(new java.awt.Dimension(600, 55));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 55);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triosignin/triologo.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1000, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        if(db.isInSystem(jTextField1.getText())) {
            if(db.hasOpenSession(jTextField1.getText())){
                db.endSession(db.getStudentID(jTextField1.getText()));
                JOptionPane.showMessageDialog(this, "You have been signed out.", "Signed Out", JOptionPane.PLAIN_MESSAGE);
                jTextField1.setText("");
            }
            else {
                db.startSession(db.getStudentID(jTextField1.getText()));
                JOptionPane.showMessageDialog(this, "You are now signed in.", "Signed In", JOptionPane.PLAIN_MESSAGE);
                jTextField1.setText("");
            }           
        }
        else {
            JOptionPane.showMessageDialog(this, "You must register.", "Please Register", JOptionPane.ERROR_MESSAGE);
            jTextField1.setText("");
            deactivateMain();
            rm.setVisible(true);
            
            rm.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                activateMain();
            }
            });
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void deactivateMain() {
        this.setEnabled(false);
    }
    
    private void activateMain() {
        this.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Holder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Holder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Holder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Holder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Holder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
